version: '3.9'

services:
  agent-bot:
    build: .
    container_name: agent-bot
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000" 
    environment:
      - PYTHONUNBUFFERED=1